@php
$selectedValues = [];

if (isset($prodAttri)) {
$saved = optional(
$prodAttri->firstWhere('attribute_name', $field['name'])
)->attribute_value;

if (is_string($saved)) {
$decoded = json_decode($saved, true);
$saved = is_array($decoded) ? $decoded : $saved;
}

if (is_array($saved)) {
$selectedValues = array_map(
fn ($value) => (string) $value,
$saved
);
} elseif (is_string($saved) && trim($saved) !== '') {
$selectedValues = array_values(
array_filter(
array_map(
'trim',
preg_split('/\s*,\s*|\s*;\s*|\r\n|\n/', $saved)
),
fn ($value) => $value !== ''
)
);
}
}

if (isset($prodAttrijson) && isset($prodAttrijson[$field['name']])) {
$saved = $prodAttrijson[$field['name']];

if (is_string($saved)) {
$decoded = json_decode($saved, true);
$saved = is_array($decoded) ? $decoded : $saved;
}

if (is_array($saved)) {
$selectedValues = array_map(
fn ($value) => (string) $value,
$saved
);
} elseif (is_string($saved) && trim($saved) !== '') {
$selectedValues = array_values(
array_filter(
array_map(
'trim',
preg_split('/\s*,\s*|\s*;\s*|\r\n|\n/', $saved)
),
fn ($value) => $value !== ''
)
);
}
}

$fieldId = 'multi_' . md5($field['name'] . uniqid('', true));
@endphp

<div class="mb-2 amazon-custom-multiselect-wrapper">

    <div
        class="amazon-custom-multiselect {{ !empty($php_errormsg) ? 'has-error' : '' }}"
        id="{{ $fieldId }}">

        {{-- Hidden inputs are generated by JS.
             Actual submitted name remains attributes[field][] --}}

        <button
            type="button"
            class="amazon-multiselect-button"
            aria-haspopup="listbox"
            aria-expanded="false">
            <span class="amazon-multiselect-text">
                Select {{ $field['title'] ?? $field['name'] }}
            </span>

            <span class="amazon-multiselect-arrow">
                ▼
            </span>
        </button>

        <div
            class="amazon-multiselect-dropdown"
            role="listbox"
            aria-multiselectable="true">

            <div class="amazon-multiselect-search-wrapper">
                <input
                    type="text"
                    class="amazon-multiselect-search"
                    placeholder="Search..."
                    autocomplete="off">
            </div>

            <div class="amazon-multiselect-options">

                @foreach($field['options'] as $option)
                @php
                $optionValue = (string) $option['value'];
                $isSelected = in_array(
                $optionValue,
                $selectedValues,
                true
                );
                @endphp

                <label
                    class="amazon-multiselect-option"
                    data-value="{{ $optionValue }}"
                    data-label="{{ strtolower($option['label']) }}">
                    <input
                        type="checkbox"
                        value="{{ $optionValue }}"
                        {{ $isSelected ? 'checked' : '' }}>

                    <span class="amazon-multiselect-checkbox"></span>

                    <span class="amazon-multiselect-label">
                        {{ $option['label'] }}
                    </span>
                </label>
                @endforeach

            </div>

        </div>
    </div>

    @if(!empty($field['description']) || $fieldHint)
    <div
        class="form-text mt-1 d-flex justify-content-between align-items-start"
        style="font-size:11px;">
        <div class="text-dark pe-2">
            {{ $field['description'] ?? '' }}
        </div>

        @if($fieldHint)
        <div class="text-primary text-end flex-shrink-0 ms-2">
            <strong>{{ $fieldHint['title'] }}:</strong>
            {{ $fieldHint['example'] }}
        </div>
        @endif
    </div>
    @endif

</div>


<style>
    .amazon-custom-multiselect-wrapper {
        width: 100%;
    }

    .amazon-custom-multiselect {
        position: relative;
        width: 100%;
    }

    .amazon-multiselect-button {
        width: 100%;
        min-height: 38px;
        padding: 6px 12px;
        border: 1px solid #aaaaeb;
        border-radius: 4px;
        background: #fff;
        color: #212529;
        font-size: small;
        text-align: left;
        display: flex;
        align-items: center;
        justify-content: space-between;
        cursor: pointer;
    }

    .amazon-multiselect-button:hover {
        border-color: #8b8be0;
    }

    .amazon-multiselect-text {
        overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis;
        padding-right: 10px;
    }

    .amazon-multiselect-arrow {
        font-size: 10px;
        flex-shrink: 0;
        color: #777;
    }

    .amazon-multiselect-dropdown {
        display: none;
        position: absolute;
        z-index: 1050;
        top: calc(100% + 3px);
        left: 0;
        width: 100%;
        max-height: 320px;
        background: #fff;
        border: 1px solid #aaaaeb;
        border-radius: 4px;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.12);
        overflow: hidden;
    }

    .amazon-custom-multiselect.open .amazon-multiselect-dropdown {
        display: block;
    }

    .amazon-custom-multiselect.has-error .amazon-multiselect-button {
        border: 3px solid #dc3545 !important;
        background: #fff0f0 !important;
    }

    .amazon-multiselect-search-wrapper {
        padding: 8px;
        border-bottom: 1px solid #eee;
        background: #fff;
    }

    .amazon-multiselect-search {
        width: 100%;
        height: 34px;
        padding: 5px 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
        outline: none;
        font-size: small;
    }

    .amazon-multiselect-search:focus {
        border-color: #8b8be0;
    }

    .amazon-multiselect-options {
        max-height: 250px;
        overflow-y: auto;
        padding: 4px 0;
    }

    .amazon-multiselect-option {
        display: flex;
        align-items: center;
        gap: 8px;
        width: 100%;
        padding: 7px 10px;
        margin: 0;
        cursor: pointer;
        font-size: small;
        font-weight: normal;
        color: #212529;
    }

    .amazon-multiselect-option:hover {
        background: #f5f5f5;
    }

    .amazon-multiselect-option input {
        position: absolute;
        opacity: 0;
        pointer-events: none;
    }

    .amazon-multiselect-checkbox {
        width: 16px;
        height: 16px;
        min-width: 16px;
        border: 1px solid #999;
        border-radius: 3px;
        background: #fff;
        position: relative;
    }

    .amazon-multiselect-option input:checked+.amazon-multiselect-checkbox {
        background: #0d6efd;
        border-color: #0d6efd;
    }

    .amazon-multiselect-option input:checked+.amazon-multiselect-checkbox::after {
        content: '';
        position: absolute;
        left: 4px;
        top: 1px;
        width: 5px;
        height: 9px;
        border: solid #fff;
        border-width: 0 2px 2px 0;
        transform: rotate(45deg);
    }

    .amazon-multiselect-label {
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }

    .amazon-multiselect-option.hidden {
        display: none;
    }

    .amazon-multiselect-empty {
        padding: 12px;
        text-align: center;
        color: #777;
        font-size: small;
    }
</style>


<script>
    (function() {

        function initAmazonCustomMultiselect(container) {

            if (!container || container.dataset.initialized === '1') {
                return;
            }

            container.dataset.initialized = '1';

            const button = container.querySelector('.amazon-multiselect-button');
            const buttonText = container.querySelector('.amazon-multiselect-text');
            const dropdown = container.querySelector('.amazon-multiselect-dropdown');
            const search = container.querySelector('.amazon-multiselect-search');
            const options = container.querySelectorAll('.amazon-multiselect-option');

            if (!button || !dropdown) {
                return;
            }

            /*
             * Create hidden inputs using the EXISTING backend name.
             *
             * attributes[field_name][]
             */
            function syncHiddenInputs() {

                container
                    .querySelectorAll('.amazon-generated-input')
                    .forEach(function(input) {
                        input.remove();
                    });

                const checked = container.querySelectorAll(
                    '.amazon-multiselect-option input[type="checkbox"]:checked'
                );

                checked.forEach(function(checkbox) {

                    const input = document.createElement('input');

                    input.type = 'hidden';

                    input.name = @json('attributes['.$field['name'].
                        '][]');

                    input.value = checkbox.value;

                    input.className = 'amazon-generated-input';

                    container.appendChild(input);
                });

                updateButtonText();
            }

            function updateButtonText() {

                const checked = Array.from(
                    container.querySelectorAll(
                        '.amazon-multiselect-option input[type="checkbox"]:checked'
                    )
                );

                if (checked.length === 0) {

                    buttonText.textContent =
                        @json('Select '.($field['title'] ?? $field['name']));

                    return;
                }

                const labels = checked.map(function(checkbox) {

                    const option = checkbox.closest(
                        '.amazon-multiselect-option'
                    );

                    return option ?
                        option.querySelector('.amazon-multiselect-label').textContent.trim() :
                        checkbox.value;
                });

                buttonText.textContent = labels.join(', ');
            }

            button.addEventListener('click', function(event) {

                event.stopPropagation();

                const isOpen = container.classList.contains('open');

                document
                    .querySelectorAll('.amazon-custom-multiselect.open')
                    .forEach(function(other) {

                        if (other !== container) {
                            other.classList.remove('open');

                            const otherButton =
                                other.querySelector('.amazon-multiselect-button');

                            if (otherButton) {
                                otherButton.setAttribute(
                                    'aria-expanded',
                                    'false'
                                );
                            }
                        }
                    });

                container.classList.toggle('open', !isOpen);

                button.setAttribute(
                    'aria-expanded',
                    String(!isOpen)
                );

                if (!isOpen) {
                    setTimeout(function() {
                        search.focus();
                    }, 50);
                }
            });

            options.forEach(function(option) {

                const checkbox = option.querySelector('input[type="checkbox"]');

                if (!checkbox) {
                    return;
                }

                checkbox.addEventListener('change', function() {
                    syncHiddenInputs();
                });

                option.addEventListener('click', function(event) {

                    if (event.target === checkbox) {
                        return;
                    }

                    checkbox.checked = !checkbox.checked;

                    checkbox.dispatchEvent(
                        new Event('change', {
                            bubbles: true
                        })
                    );
                });
            });

            search.addEventListener('input', function() {

                const term = search.value.trim().toLowerCase();

                let visibleCount = 0;

                options.forEach(function(option) {

                    const label =
                        option.dataset.label || '';

                    const visible =
                        term === '' || label.includes(term);

                    option.classList.toggle(
                        'hidden',
                        !visible
                    );

                    if (visible) {
                        visibleCount++;
                    }
                });

                let emptyMessage =
                    container.querySelector('.amazon-multiselect-empty');

                if (visibleCount === 0) {

                    if (!emptyMessage) {

                        emptyMessage =
                            document.createElement('div');

                        emptyMessage.className =
                            'amazon-multiselect-empty';

                        emptyMessage.textContent =
                            'No options found';

                        container
                            .querySelector('.amazon-multiselect-options')
                            .appendChild(emptyMessage);
                    }

                } else if (emptyMessage) {

                    emptyMessage.remove();
                }
            });

            dropdown.addEventListener('click', function(event) {
                event.stopPropagation();
            });

            /*
             * Close when clicking outside.
             */
            document.addEventListener('click', function(event) {

                if (!container.contains(event.target)) {

                    container.classList.remove('open');

                    button.setAttribute(
                        'aria-expanded',
                        'false'
                    );
                }
            });

            /*
             * Initial selected values.
             */
            syncHiddenInputs();
        }


        function initializeAllAmazonMultiselects() {

            document
                .querySelectorAll('.amazon-custom-multiselect')
                .forEach(function(container) {
                    initAmazonCustomMultiselect(container);
                });
        }


        if (document.readyState === 'loading') {

            document.addEventListener(
                'DOMContentLoaded',
                initializeAllAmazonMultiselects
            );

        } else {

            initializeAllAmazonMultiselects();
        }


        /*
         * Supports dynamically rendered fields as well.
         */
        const observer = new MutationObserver(function() {

            initializeAllAmazonMultiselects();

        });

        observer.observe(document.body, {
            childList: true,
            subtree: true
        });

    })();
</script>