name = "Zeosync"
client_id = "cc04d2b21de39debde846f2b0f70a763"
application_url = "https://zeosync.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
# The permissions your app needs
scopes = "read_analytics,read_customer_merge,write_customer_merge,read_delivery_customizations,write_delivery_customizations,read_price_rules,write_price_rules,read_discounts,write_discounts,write_draft_orders,read_draft_orders,read_fulfillments,write_fulfillments,read_gift_cards,write_gift_cards,write_inventory,read_inventory,write_inventory_shipments,read_inventory_shipments,write_inventory_shipments_received_items,read_inventory_shipments_received_items,write_inventory_transfers,read_inventory_transfers,write_locations,read_locations,write_order_edits,read_order_edits,read_orders,write_orders,read_product_listings,write_product_listings,read_products,write_products,write_reports,read_reports,read_returns,write_returns,read_content,write_content,customer_read_companies,customer_write_companies,customer_write_customers,customer_read_customers,customer_read_orders,customer_write_orders,unauthenticated_read_product_listings,shop_app:oauth"

[auth]
# This tells Shopify where to send the user to start the session
redirect_urls = [
  "https://zeosync.app/callback",
  "https://zeosync.app/"
]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://zeosync.app/webhooks/app-uninstalled"


[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "https://zeosync.app/webhooks/shopify/orders/create"


[[webhooks.subscriptions]]

uri = "https://zeosync.app/customers/data_request"
compliance_topics = ["customers/data_request"]

[[webhooks.subscriptions]]
uri = "https://zeosync.app/customers/redact"
compliance_topics = ["customers/redact"]

[[webhooks.subscriptions]]
uri = "https://zeosync.app/shop/redact"
compliance_topics = ["shop/redact"]

